name: Fetch Google Sheet Data

on:
  workflow_dispatch: # Manual trigger from GitHub UI
  repository_dispatch: # Triggered by Google Apps Script
    types: [sheet-updated] # Must match the event in the Apps Script

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run supabase script
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: node supabase.js
